DROP DATABASE IF EXISTS QLTOANHA;
CREATE DATABASE IF NOT EXISTS QLTOANHA;

USE QLTOANHA;

CREATE TABLE NHAN_VIEN_TOA(
    MA_NV VARCHAR(50) NOT NULL,
    TEN VARCHAR(50) NOT NULL,
    NS DATE,
    DIA_CHI VARCHAR(100),
    SDT VARCHAR(50),
    PRIMARY KEY (MA_NV)
);

CREATE TABLE NHAN_VIEN_CT(
    MA_NV VARCHAR(50) NOT NULL,
    MA_CT VARCHAR(50) NOT NULL,
    TEN VARCHAR(50) NOT NULL,
    NGAY_SINH DATE,
    CMT VARCHAR(100) UNIQUE,
    SDT VARCHAR(10),
    PRIMARY KEY (MA_NV),
    FOREIGN KEY (MA_CT) REFERENCES CONG_TY(MA_CT)
);

CREATE TABLE CONG_TY(
    MA_CT VARCHAR(50) NOT NULL,
    TEN_CT VARCHAR(50) NOT NULL,
    MST VARCHAR(50) NOT NULL UNIQUE,
    LINH_VUC VARCHAR(50),
    DIA_CHI VARCHAR(50),
    SDT VARCHAR(10),
    SO_NV INT,
    DIEN_TICH FLOAT,
    PRIMARY KEY (MA_CT)
);

CREATE TABLE DICH_VU(
    MA_DV VARCHAR(50) NOT NULL,
    TEN_DV VARCHAR(50) NOT NULL,
    LOAI_DV VARCHAR(50),
    DON_GIA_CS FLOAT,
    PRIMARY KEY (MA_DV)
);

CREATE TABLE SU_DUNG(
    MA_CT VARCHAR(50) NOT NULL,
    MA_DV VARCHAR(50) NOT NULL,
    NGAY_BD DATETIME DEFAULT CURRENT_TIMESTAMP,
    NGAY_KT DATE,
    DON_GIA_RIENG INT,
    PRIMARY KEY (MA_CT, MA_DV),
    FOREIGN KEY (MA_CT) REFERENCES CONG_TY(MA_CT),
    FOREIGN KEY (MA_DV) REFERENCES DICH_VU(MA_DV)
);

CREATE TABLE THE_RA_VAO(
    MA_THE VARCHAR(50) NOT NULL,
    MA_NV VARCHAR(50) NOT NULL,
    PRIMARY KEY (MA_THE),
    FOREIGN KEY (MA_NV) REFERENCES NHAN_VIEN_CT(MA_NV)
);

CREATE TABLE LAM_VIEC(
    MA_LV VARCHAR(50) NOT NULL,
    MA_DV VARCHAR(50) NOT NULL,
    MA_NV VARCHAR(50) NOT NULL,
    VI_TRI VARCHAR(50) NOT NULL,
    RATE_LUONG VARCHAR(50) NOT NULL,
    NGAY_BD DATE NOT NULL,
    NGAY_KT DATE NOT NULL,
    PRIMARY KEY (MA_LV, MA_DV, MA_NV),
    FOREIGN KEY (MA_DV) REFERENCES DICH_VU(MA_DV),
    FOREIGN KEY (MA_NV) REFERENCES NHAN_VIEN_TOA(MA_NV)
);

CREATE TABLE RA_VAO(
    MA_RV VARCHAR(50) NOT NULL,
    MA_THE VARCHAR(50) NOT NULL,
    VI_TRI VARCHAR(50) NOT NULL,
    TRANG_THAI VARCHAR(20) NOT NULL,
    CHECK_TIME DATETIME NOT NULL,
    PRIMARY KEY (MA_RV, MA_THE),
    FOREIGN KEY (MA_THE) REFERENCES THE_RA_VAO(MA_THE)
);

#THEM DATA DICH VU
INSERT INTO DICH_VU
VALUES
('DV01', 'VE SINH', 'CHUAN', '1000000'),
('DV02', 'BAO VE' , 'CHUAN' , '1000000'),
('DV03', 'AN UONG', 'EXTRA', '4000000' ),
('DV04', 'TRONG XE', 'EXTRA', '1000000'),
('DV05', 'BAO TRI THIET BI', 'EXTRA', '1000000')
;

#THEM CONG TY
INSERT INTO CONG_TY
VALUES
('CT01', 'MULTICAMPUS', '0122112', 'CONG NGHE', 'P201', '0123456789', 15, 120),
('CT02', 'NIPA', '0122113', 'GIAO DUC', 'P301', '0123556789', 9, 80)
;

#THEM NHAN VIEN
INSERT INTO NHAN_VIEN_CT
VALUES
('E0001','CT01', 'DINH BAC', '1997-10-10', '00111888', '038777621'),
('E0002','CT01', 'DINH TU', '1992-10-10', '00121888', '038767621'),
('E0003','CT01', 'DINH BINH', '1999-10-10', '00131888', '038757621')
;

#TU DONG THEM SU DUNG DICH VU MAC DINH
DELIMITER //
CREATE TRIGGER DV_DEFAULT AFTER INSERT ON CONG_TY FOR EACH ROW
    BEGIN
        DECLARE GIA_CS_1 FLOAT;
        DECLARE GIA_CS_2 FLOAT;
        #TU DONG THEM DICH VU BAO VE VA VE SINH LA DINH VU MAC DINH
        SELECT DON_GIA_CS INTO GIA_CS_1 FROM DICH_VU WHERE TEN_DV = 'VE SINH';
        SELECT DON_GIA_CS INTO GIA_CS_2 FROM DICH_VU WHERE TEN_DV = 'BAO VE';
        #INSERT VAO BANG
        INSERT INTO SU_DUNG(MA_CT, MA_DV, DON_GIA_RIENG) VALUES (NEW.MA_CT, 'DV01', GIA_CS_1);
        INSERT INTO SU_DUNG(MA_CT, MA_DV, DON_GIA_RIENG) VALUES (NEW.MA_CT, 'DV02', GIA_CS_1);
    END
//

DROP TRIGGER DV_DEFAULT;

#TU DONG UPDATE SO NHAN VIEN
DELIMITER //
CREATE TRIGGER ADD_SLNV AFTER INSERT ON NHAN_VIEN_CT FOR EACH ROW
    BEGIN
        UPDATE CONG_TY SET SO_NV = SO_NV + 1 WHERE CONG_TY.MA_CT = NEW.MA_CT;
    END
//

DELIMITER //
CREATE TRIGGER SUBTRACT_SLNV AFTER DELETE ON NHAN_VIEN_CT FOR EACH ROW
    BEGIN
        UPDATE CONG_TY SET SO_NV = SO_NV - 1 WHERE CONG_TY.MA_CT = OLD.MA_CT;
    END
//

DELIMITER //
CREATE TRIGGER UPDATE_SLNV AFTER UPDATE ON NHAN_VIEN_CT FOR EACH ROW
    BEGIN
        DECLARE SO_NV_CU INT;
        DECLARE SO_NV_MOI INT;
        SET SO_NV_CU = 0;
        SET SO_NV_MOI = 0;

        SELECT COUNT(*) INTO SO_NV_CU FROM NHAN_VIEN_CT WHERE MA_CT = OLD.MA_CT;
        SELECT COUNT(*) INTO SO_NV_MOI FROM NHAN_VIEN_CT WHERE MA_CT = NEW.MA_CT;

        UPDATE CONG_TY SET SO_NV = SO_NV_CU WHERE CONG_TY.MA_CT = OLD.MA_CT;
        UPDATE CONG_TY SET SO_NV = SO_NV_MOI WHERE CONG_TY.MA_CT = NEW.MA_CT;
    END
//

#TU DONG TANG GIA DICH VU KHI TANG SL NHAN VIEN
DELIMITER //
create trigger UPDATE_GIADV after UPDATE ON congty FOR EACH ROW
    BEGIN
        DECLARE SoNVHT int;
        DECLARE PhanTram float;
        DECLARE PhanTram2 float;
        DECLARE DienTich float;
        DECLARE GiaBD float;

        SELECT DonGiaCS INTO  GiaBD FROM DichVu,Sudung,CongTy
        WHERE DichVu.MaDV = Sudung.MaDV AND Sudung.MaCT = CongTy.MaCT;

        #SET SoNVHT = NEW.SoNV;
        SELECT SoNV INTO SoNVHT FROM CongTy WHERE SoNV = NEW.SoNV GROUP BY CongTy.MaCT;
        SELECT CongTy.DienTich INTO DienTich FROM CongTy WHERE DienTich = NEW.DienTich GROUP BY CongTy.MaCT;
        #SET DienTich = NEW.DienTich;

        IF SoNVHT > 10
            THEN BEGIN
                SET PhanTram = ((SoNVHT - 10)/5)*0.05;
            END;
        END IF;

        IF SoNVHT > 10
            THEN BEGIN
                SET PhanTram2 = ((DienTich - 100)/10)*0.05;
            END;
        END IF;

        UPDATE Sudung SET DonGiaRieng = GiaBD + GiaBD * PhanTram + GiaBD * PhanTram2
        WHERE Sudung.MaCT = NEW.MaCT;
    END
//
DROP TRIGGER UPDATE_GIADV;